package dataAccess;

import java.sql.*;

public class DatabaseConnection {
    private String url = "jdbc:mysql://localhost:3306/quiz";
    private Connection connection = null;
    private String username = "root";
    private String password = "P@ssw0rd";//"P@ssw0rd";

    public DatabaseConnection()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection(url, username, password);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    public PreparedStatement getPreparedStatement(String query)
    {
        PreparedStatement ps = null;
        try {
            ps = connection.prepareStatement(query);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return ps;
    }

    public PreparedStatement getPreparedStatement(String query,int autoGeneratedkeys)
    {
        PreparedStatement ps = null;
        try {
            ps = connection.prepareStatement(query, autoGeneratedkeys);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return ps;
    }

}
